import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Fustat } from "next/font/google";
import "./globals.css";
import { CreditsProviderWrapper } from "./components/credits-provider-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const fustat = Fustat({
  variable: "--font-fustat",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fustat.variable} antialiased`}
      >
        <CreditsProviderWrapper>{children}</CreditsProviderWrapper>
      </body>
    </html>
  );
}
